### ISSUE TITLE
ToDo 1.0 release

### ISSUE THREAD

**Issue by fallenhitokiri** [fallenhitokiri/leeroyci#3]
- [x] HipChat integration
- [ ] GitLab integration
- [ ] Bitbucket integration (git, eventually Mercurial)
- [x] Campfire notifications
- [ ] support for custom templates and notifications
- [x] user authentication (status pages)
- [x] configuration of repositories through the web interface
- [x] configuration validation
- [x] individual tokens and servers for each repository
- [ ] website with a browsable documentation and more default snippets
- [x] access all builds through an API that returns JSON

**Comment by fallenhitokiri** [comment]
https://trello.com/b/kPVNje2s/leeroyci - Trello board to follow what's going on
